/*
Copyright 2024 Democracy Developers

The Raire Service is designed to connect colorado-rla and its associated database to
the raire assertion generation engine (https://github.com/DemocracyDevelopers/raire-java).

This file is part of raire-service.

raire-service is free software: you can redistribute it and/or modify it under the terms
of the GNU Affero General Public License as published by the Free Software Foundation, either
version 3 of the License, or (at your option) any later version.

raire-service is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License along with
raire-service. If not, see <https://www.gnu.org/licenses/>.
*/

package au.org.democracydevelopers.raireservice.response;

import au.org.democracydevelopers.raire.algorithm.RaireResult;

/**
 * The success response to a GetAssertionsRequest, consisting of
 * Metadata: the contest name, candidate names, risk limit, and array of current assertion risks
 * Solution: the list of assertions generated by raire-java, plus some other auxiliary information such as
 * time taken for generation, minimum margin and maximum difficulty.
 */
public class GetAssertionsResponse {

  /**
   * Contest metadata for the assertion visualiser to read and convey to the user. Currently
   * includes both basic contest information (contest name, list of candidate names) and RLA information
   * (risk limit, and an array of current risk estimates, one for each assertion).
   */
  public final Metadata metadata;

  /**
   * The solution generated by raire-java, consisting of the list of assertions plus some auxiliary information.
   */
  public final RaireResult solution;

  /**
   * All args constructor.
   * @param metadata contest metadata including contest name, candidate list, risk information.
   * @param solution the solution generated by raire-java, including the list of assertions and auxiliary
   *                 information.
   */
  public GetAssertionsResponse(Metadata metadata, RaireResult solution) {
    this.metadata = metadata;
    this.solution = solution;
  }
}
